export const images = {
  imageSuccessLight: require('./imageSuccessLight.png'),
  imageSuccessDark: require('./imageSuccessDark.png'),
  imageRatingLight: require('./imageRatingLight.png'),
  imageRatingDark: require('./imageRatingDark.png'),
  imageSadFace: require('./sadFace.png'),
  imageHappyFace: require('./happyFace.png'),
  accommodationLight: require('./accommodationLight.png'),
  accommodationDark: require('./accommodationDark.png'),
  eventLight: require('./eventLight.png'),
  eventDark: require('./eventDark.png'),
  placeToEatLight: require('./placeToEatLight.png'),
  placeToEatDark: require('./placeToEatDark.png'),
  handshakeDark: require('./handshakeDark.png'),
  handshakeLight: require('./handshakeLight.png'),
};
