export type IconsNames =
  | 'bicycle'
  | 'bookmark'
  | 'bookmarkFilled'
  | 'check'
  | 'chevron'
  | 'compass'
  | 'cross'
  | 'error'
  | 'home'
  | 'homeFilled'
  | 'mapMarkerGray'
  | 'marker'
  | 'markerFilled'
  | 'paw'
  | 'search';
