export const ACTIONS = {
  BOOTSTRAP_START: 'BOOTSTRAP_START',
  BOOTSTRAP_FINISH: 'BOOTSTRAP_FINISH',
  CLEAR_ERROR_BY_ACTION_TYPE: 'CLEAR_ERROR_BY_ACTION_TYPE',
  CLEAR_SUCCESS_BY_ACTION_TYPE: 'CLEAR_SUCCESS_BY_ACTION_TYPE',
};
