import {StyleSheet} from 'react-native';

export const FONTS = {
  primary: 'Montserrat-SemiBold',
  primaryBold: 'Montserrat-Bold',
  secondaryBold: 'Montserrat-Bold',
  secondarySemibold: 'Montserrat-SemiBold',

  bold: 'Montserrat-Bold',
  semibold: 'Montserrat-SemiBold',
  regular: 'Montserrat-Regular',
};

export const FONTS_STYLES = StyleSheet.create({
  bold15: {
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'System',
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  semibold20: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'System',
    letterSpacing: -0.3,
    lineHeight: 22,
  },
  semibold18: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'System',
    letterSpacing: -0.3,
    lineHeight: 20,
  },
  semibold16: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'System',
    letterSpacing: -0.3,
    lineHeight: 20,
  },
  semibold15: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'System',
    letterSpacing: -0.3,
    lineHeight: 20,
  },
  semibold14: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'System',
    lineHeight: 22,
  },
  semibold12: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: FONTS.semibold,
    lineHeight: 15,
    letterSpacing: 0.2,
  },
  regular16: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 22,
  },
  regular15: {
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 22,
  },
  regular14: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 24,
  },
  regular12: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 16,
  },
  regular13: {
    fontSize: 13,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 18,
    letterSpacing: -0.08,
  },
  regular17: {
    fontSize: 17,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 22,
    letterSpacing: -0.408,
  },
  regular22: {
    fontSize: 22,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 24,
    letterSpacing: 0.35,
  },
  regular24: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'System',
    lineHeight: 28,
  },

  headlineRegular: {
    fontSize: 18,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 24,
  },
  title3Bold: {
    fontSize: 24,
    fontWeight: '600',
    fontFamily: 'System',
    lineHeight: 32,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 24,
  },
  text_12_20_400: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 20,
  },
  subheadline: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'System',
    lineHeight: 24,
  },
  text_16_24_400: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 24,
  },
  text_14_20_500: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'System',
    lineHeight: 20,
  },
  text_12_16_400: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 16,
  },
  text_14_24_400: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 24,
  },
  text_15_24_400: {
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'System',
    lineHeight: 24,
  },
  text_16_20_600: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'System',
    lineHeight: 20,
  },
});

export const FONTS_PRESETS = StyleSheet.create({
  largeTitleRegular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 48,
    lineHeight: 56,
  },
  largeTitleBold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 48,
    lineHeight: 56,
  },
  title1Regular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 34,
    lineHeight: 44,
  },
  title2Regular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 32,
    lineHeight: 40,
  },
  title2Bold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 32,
    lineHeight: 40,
  },
  title3Regular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 24,
    lineHeight: 32,
  },
  title3Bold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 24,
    lineHeight: 32,
  },
  headlineRegular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 18,
    lineHeight: 24,
  },
  headlineBold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 18,
    lineHeight: 24,
  },
  subheadlineRegular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 16,
    lineHeight: 24,
  },
  subheadlineBold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 16,
    lineHeight: 24,
  },
  bodyRegular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 16,
    lineHeight: 24,
  },
  bodyBold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 16,
    lineHeight: 24,
  },
  calloutRegular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 16,
    lineHeight: 24,
  },
  calloutBold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 16,
    lineHeight: 24,
  },
  footnoteRegular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 14,
    lineHeight: 20,
  },
  footnoteBold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 14,
    lineHeight: 20,
  },
  caption1Regular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 12,
    lineHeight: 16,
  },
  caption1Bold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 12,
    lineHeight: 16,
  },
  caption2Regular: {
    fontWeight: '400',
    fontFamily: 'System',
    fontSize: 11,
    lineHeight: 13,
  },
  caption2Bold: {
    fontWeight: '700',
    fontFamily: 'System',
    fontSize: 11,
    lineHeight: 13,
  },
});
